### ISSUE TITLE
Fetching the navigation

### ISSUE THREAD

**Issue by rmakara** [elkmod/SwagVueStorefront#15]
**Context**
During the workshop we had a short discussion associated with fetching the navigation. One way that we see to display the navigation in the frontend is to use /category endpoint to get the whole structure of categories, external links and structing elements. However, this endpoint is pretty big. Right now we are not 100% sure what would be the most efficient way to fetch the navigation / menu. How do you currently solve that in Shopware? What's the best way to fetch it in a light way? Assuming the eCommerce may have even more than 1000 categories to display in very nested menu, we would love to find the way of fetching not only everything at once but also sub-menu or level only. (

**Comment by elkmod** [comment]
**Proposal for navigation endpoint**

The endpoint should give clients the ability to *fetch navigation elements* (=> categories) along with their corresponding route path.

**Request**

*rootNode*: Specifies the root node from which to start resolving the navigation tree (if not given, fetch from root category)

*depth*: The number of tree layers to be resolved. 1 yields only the first layer, 2 yields first and second etc. 0 is invalid. -1 yields the full tree.

```json
{
	"rootNode": "f4047ed0895a413488609a924fa9cf0a",
	"depth": 1
}
```

**Response**

```json
{
	"count": 3,
	"elements": [{
		"name": "Games & Home",
		"path": "/Games-Home"
	},
	{
		"name": "Toys & Music",
		"path": "/Toys-Music"
	},
	{
		"name": "Jewelry & Industrial",
		"path": "/Jewelry-Industrial"
	}]
}
```

**Additional Cases**

The final output will include additional information about the navigation element (sometimes they are just there for a structural purpose and have no corresponding page). Another case is that the category is used as an external reference, hence the information is needed as well.

**Comment by mkucmus** [comment]
the assumptions are correct :+1:

**Comment by elkmod** [comment]
**Proposal**

Include the `resourceType` of the resulting page within every navigation element. So eventually one element within the response will look like:

```json
{
  "name": "Cars & Food",
  "route": {
    "pathInfo": "/Cars-Food",
    "resourceType": "frontend.navigation.page"
  },
  "children": null
}
```

This way we can determine the page type *before* actually sending a page request to resolve the page. Could result in pre-rendering of the component and having eventual content hydration. Other use 

> **Important** - The naming of routes should be consistent with the one provided by [`/vsf/routes`](https://github.com/elkmod/SwagVueStorefront/blob/master/_doc/swagger.yaml#L172) and the breadcrumbs in `/vsf/page`

**Comment by patzick** [comment]
thanks, @elkmod :) I will address here to two points

### 1. depth
> depth: The number of tree layers to be resolved. 1 yields only the first layer, 2 yields first and second etc. 0 is invalid. -1 yields the full tree.

shouldn't `0` be valid and return just single level without children? I also believe this would be the best default value ;D

### 2. proposal
I think it would be a little bit simpler to just add another field instead of nesting a whole routing. What would you say about something like this?
```json
{
  "name": "Cars & Food",
  "path": "/Cars-Food",
  "resourceType": "frontend.navigation.page",
  "children": null
}
```

**Comment by mkucmus** [comment]
@elkmod Is it possible to recognize the "/" route for cms pages within the page resolver? 
We need to render the home page as a CmsPage, and we've found out, we could use the Category Entry point (set in sales channel settings) as a home page representation. 
Going this way is it possible to add to the navigation the Root Category (Catalogue 1) which is available under the "/" path for depth 0?
In the future, it could be set on some kind of settings page like "Cms for Homepage", but for now is good and easy enough to get the navigation and generic cms system fully working.

**Comment by elkmod** [comment]
@mkucmus could you please confirm:

You're describing two this:

 1. Adding a resolve for the `/` route within the page resolver.
 2. Also fetching the root category within the `/navigation` endpoint. So more generically speaking, also fetch the "containing" category and not only its children?

**Comment by elkmod** [comment]
@patzick 
My thought concerning the nested nested `route` object was that we ultimately have a consistent structure of what we call "routes" within the application. A route can be associated "pages" (or, more generally "resources") and always has at least a path and a resource type (in order for you to determine the type of page). Wdyt?

It is a reasonable behavior to fetch only the root category when you provide `depth = 0` but would you actually ever need it? - It's connected to the comment above. In order to display the first level "main navigation" you need the root category and all of its first level children. I think the best option is to:

Always show the root category (i.e. sales channel root or the one with the id provided by the `rootNode` parameter.) and the rely on `depth` to either:

`depth=0` - fetch no children
`depth=1` - fetch first level
`depth=2` - fetch second level, etc.
`depth=-1` - fetch full tree

**Comment by patzick** [comment]
@elkmod you're right with this object if we'd like to have same structure within the application. In this case, could we also add this into products objects in listing on the category page?

My proposition of 0 depth was addressing your example:) case is the main menu. You wrote example
```json
/// -> request 
{
	"rootNode": "f4047ed0895a413488609a924fa9cf0a",
	"depth": 1
}

/// -> response

{
  "count": 5,
  "elements": [
    {
      "name": "Games & Home",
      "path": "/Games-Home",
      "children": [
        {
          "name": "Toys & Music",
          "path": "/Games-Home/Toys-Music",
          "children": null
        },
        {
          "name": "Jewelry & Industrial",
          "path": "/Games-Home/Jewelry-Industrial",
          "children": null
        }
      ]
    },
    {
      "name": "Cars & Food",
      "path": "/Cars-Food",
      "children": [
        {
          "name": "Phones & Art",
          "path": "/Cars-Food/Phones-Art",
          "children": null
        }
      ]
    }
  ]
}
```

and for main menu, we need 0 depth, only elements, so example I ment was:

```json
/// -> request 
{
	"rootNode": "f4047ed0895a413488609a924fa9cf0a",
	"depth": 0
}

/// -> response

{
  "count": 5,
  "elements": [
    {
      "name": "Games & Home",
      "path": "/Games-Home",
    },
    {
      "name": "Cars & Food",
      "path": "/Cars-Food",
    }
  ]
}
```

**Comment by elkmod** [comment]
Okay, I get your point. But @mkucmus was asking about fetching the root category as well, which I didn't mention in my example at all. More like:

**Request depth=0**
```
{
	"rootNode": "f4047ed0895a413488609a924fa9cf0a",
	"depth": 0
}
```

**Response depth=0**
```
{
  "count": 2,
  "navigation": {
      "name": "Catalogue #1",
      "path": "/"
  }
}
```

**Request depth=1**
```
{
	"rootNode": "f4047ed0895a413488609a924fa9cf0a",
	"depth": 1
}
```

**Response depth=1**
```
{
  "count": 2,
  "navigation": {
      "name": "Catalogue #1",
      "path": "/",
      "children": [
        {
          "name": "Games & Home",
          "path": "/Games-Home",
        },
        {
          "name": "Cars & Food",
          "path": "/Cars-Food",
        }
      ]
  }
}
```

**Comment by patzick** [comment]
@elkmod yeah, and now I see your point of question about depth 0 ;D

I completely agree that `depth: 1` should be a default then, but I'd leave still a possibility to get depth 0. Example:
We have a product somewhere and we have its category id. Or somewhere we have category id. We don't need to display anything but a link to this category, so we don't need to load category endpoint with the whole object and just invoke this endpoint to fetch navigation to it.

So, to sum up, would that be a final proposition?
```
{
  "rootNode": "f4047ed0895a413488609a924fa9cf0a",
}
```
and here `depth 1` is default, response:
```json
{
  "name": "Catalogue #1",
  "route": {
    "path": "/",
    "resourceType": "frontend.navigation.page"
  },
  "children": [
    {
      "name": "Games & Home",
      "route": {
          "pathInfo": "/Games-Home",
          "resourceType": "frontend.navigation.page"
        },
    },
    {
      "name": "Cars & Food",
      "route": {
          "pathInfo": "/Cars-Food",
          "resourceType": "frontend.navigation.page"
        },
    }
  ] 
}
```


AND
Could we also make rootNode default to be real root category?

**Comment by mkucmus** [comment]
I've tried out to fetch the navigation.
- default rootNode points to the navigationEntrypoint (sales channel settings?)
- rootNode parameter is respected and enables us to fetch the navigation with provided rootNode as a starting node
- depth: 1 is the default one, and any other > 1 is respected

thanks @elkmod :+1:
