### ISSUE TITLE
External Checkout plugin

### ISSUE THREAD

**Issue by mkucmus** [elkmod/SwagVueStorefront#25]
We should be able to continue checkout on the Shopware platform with given sw-context-token with all the data synchronized.

### Scenario
1. customer adds to cart a product
2. customer's session (stick to sw-context-token) contains the data like items in cart,  currency, language, etc.
3. regardless he's logged or not he proceeds to the checkout by clicking  "go to checkout"
4. the redirection to Shopware _/checkout/external?sw-context-token=pLHK2L0Fts26xJOqVknKa5mEFJOojvuN&checksum=89c7b6c7a25c2426e00822852e5a1b25_  is being performed with all the necessary data:
- sw-context-token - to recognize the session the customer/cart belongs to
- checksum - which is a hash made by token, customerId, or even more fields to make the redirection safe against the unwanted taking over the session
5. Controller, where the _/checkout/external_ traffic goes to, should parse sw-context-token, validate the checksum and perform/or not the login process (if the customer wasn't logged in) or showing the checkout page (frontend).
6. The context is being merged or stays the same as we had as a sales-channel-api user.
7. Depending on the context, the customer is logged in or not, all the data mentioned in point 2 are the same.
8. after the checkout is successfully finished, the order is placed -  instead of the default success page at the Shopware side - the customer should be redirected to the thank-you-page hosted on the vue-storefront application where the shopping process started at. The URL could be optional (if URL exists - redirect to vsf, show default SW6 success page if not). It may be configurable at the SW6 administration panel or hardcoded.
9. if the success page was shown - the cart on both sides should be cleared. 

### Result
1. Shopware enables the external checkout's requests handling and setting the right context (based on incoming context)
2. Shopware enables the success-page redirection to the pointed URL (in the admin panel or hardcoded/generated once)

### Problems
1. currently the customers can be assigned only to the one sales channel
2. ... TODO :)

**Comment by elkmod** [comment]
Closed due to implementation priority for internal checkout.
